# Generated by Django 2.2.1 on 2019-07-31 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='inputform',
        ),
    ]
