# Generated by Django 2.2.1 on 2019-07-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inputform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('product_name', models.TextField()),
                ('location', models.TextField()),
                ('person_num', models.TextField()),
                ('price', models.TextField()),
                ('link', models.TextField()),
                ('account', models.TextField()),
                ('date_limit', models.DateTimeField(verbose_name='date published')),
                ('explanation', models.CharField(max_length=300)),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
    ]
