# Generated by Django 2.2.1 on 2019-07-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputform',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
