# Generated by Django 2.2.4 on 2019-08-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190807_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_num',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.TextField(blank=True),
        ),
    ]
