# Generated by Django 2.2.1 on 2019-07-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190731_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputform',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
