# Generated by Django 2.2.1 on 2019-07-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190801_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputform',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
